default_email: "rubyconfar@gmail.com"
smtp_settings: 
  url: "smtp://localhost:1025"

twitter:
  access_token: "REPLACE ME"
  access_token_secret: "REPLACE ME"

twitter:
  access_token: "REPLACE ME"
  access_token_secret: "REPLACE ME"
